# mouse 
set -g mouse on

# set prefix keybind
unbind C-b
set -g prefix C-a
bind C-a send-prefix


# split the window
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# pane change
bind h select-pane -L
bind l select-pane -R
bind j select-pane -D
bind k select-pane -U

# terminal color
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
